# Docker-compose

version: '3.8'

services:
  futbol-analytics:
    build: .
    container_name: futbol-analytics
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped